version: '3'
services:
  db:
    image: postgres
    ports:
      - "5433:5433"
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .docker-env
    entrypoint: ./docker/bin/run.sh
