assessment:
  risk:
    sections:
      risk_to_self:
        questions:
          -
            name: acct_status
            mandatory: true
            relevant_answers:
              - open
              - post_closure
              - closed_in_last_6_months
            details:
              - date_of_most_recently_closed_acct
              - acct_status_details
      risk_from_others:
        questions:
          -
            name: rule_45
            mandatory: true
          -
            name: csra
            mandatory: true
            relevant_answers:
              - high
          -
            name: victim_of_abuse
            mandatory: true
          -
            name: high_profile
            mandatory: true
      violence:
        questions:
          -
            name: violence_due_to_discrimination
            mandatory: true
            dependencies:
              - risk_to_females
              - homophobic
              - racist
              - other_violence_due_to_discrimination
          -
            name: violence_to_staff
            mandatory: true
            dependencies:
              - violence_to_staff_custody
              - violence_to_staff_community
          -
            name: violence_to_other_detainees
            mandatory: true
            dependencies:
              - co_defendant
              - gang_member
              - other_violence_to_other_detainees
        subsections:
          discrimination:
            questions:
              -
                name: risk_to_females
              -
                name: homophobic
              -
                name: racist
              -
                name: other_violence_due_to_discrimination
          violence_to_staff:
            questions:
              -
                name: violence_to_staff_custody
              -
                name: violence_to_staff_community
          violence_to_other_detainees:
            questions:
              -
                name: co_defendant
              -
                name: gang_member
              -
                name: other_violence_to_other_detainees
          violence_to_general_public:
            questions:
              -
                name: violence_to_general_public
                mandatory: true
      hostage_taker:
        questions:
          -
            name: hostage_taker
            mandatory: true
            dependencies:
              - staff_hostage_taker
              - prisoners_hostage_taker
              - public_hostage_taker
          -
            name: staff_hostage_taker
            details:
              - date_most_recent_staff_hostage_taker_incident
          -
            name: prisoners_hostage_taker
            details:
              - date_most_recent_prisoners_hostage_taker_incident
          -
            name: public_hostage_taker
            details:
              - date_most_recent_public_hostage_taker_incident
      harassments:
        questions:
          -
            name: intimidation
            mandatory: true
            dependencies:
              - intimidation_to_staff
              - intimidation_to_public
              - intimidation_to_other_detainees
              - intimidation_to_witnesses
        subsections:
          harassment:
            questions:
              -
                name: harassment
                mandatory: true
          intimidation:
            questions:
              -
                name: intimidation_to_staff
              -
                name: intimidation_to_public
              -
                name: intimidation_to_other_detainees
              -
                name: intimidation_to_witnesses
      sex_offences:
        questions:
          -
            name: sex_offence
            mandatory: true
            dependencies:
              - sex_offence_adult_male_victim
              - sex_offence_adult_female_victim
              - sex_offence_under18_victim
          -
            name: sex_offence_adult_male_victim
          -
            name: sex_offence_adult_female_victim
          -
            name: sex_offence_under18_victim
      security:
        questions:
          -
            name: previous_escape_attempts
            mandatory: true
            dependencies:
              - prison_escape_attempt
              - court_escape_attempt
              - police_escape_attempt
              - other_type_escape_attempt
        subsections:
          escape_status:
            questions:
              -
                name: current_e_risk
                mandatory: true
                details:
                  - current_e_risk_details
          previous_escape_attempts:
            questions:
              -
                name: prison_escape_attempt
              -
                name: court_escape_attempt
              -
                name: police_escape_attempt
              -
                name: other_type_escape_attempt
          category_a:
            questions:
              -
                name: category_a
                mandatory: true
          escort_details:
            questions:
              -
                name: escort_risk_assessment
                mandatory: true
                details:
                  - escort_risk_assessment_completion_date
              -
                name: escape_pack
                mandatory: true
                details:
                  - escape_pack_completion_date
      substance_misuse:
        questions:
          -
            name: substance_supply
            mandatory: true
            dependencies:
              - trafficking_drugs
              - trafficking_alcohol
          -
            name: trafficking_drugs
          -
            name: trafficking_alcohol
      concealed_weapons:
        questions:
          -
            name: conceals_weapons
            mandatory: true
          -
            name: conceals_drugs
            mandatory: true
          -
            name: conceals_mobile_phone_or_other_items
            mandatory: true
            dependencies:
              - conceals_mobile_phones
              - conceals_sim_cards
              - conceals_other_items
          -
            name: conceals_mobile_phones
          -
            name: conceals_sim_cards
          -
            name: conceals_other_items
      arson:
        questions:
          -
            name: arson
            mandatory: true
  healthcare:
    sections:
      physical:
        questions:
          -
            name: physical_issues
            mandatory: true
      mental:
        questions:
          -
            name: mental_illness
            mandatory: true
          -
            name: phobias
            mandatory: true
      social:
        questions:
          -
            name: personal_hygiene
            mandatory: true
          -
            name: personal_care
            mandatory: true
      allergies:
        questions:
          -
            name: allergies
            mandatory: true
      needs:
        questions:
          -
            name: dependencies
            mandatory: true
          -
            name: has_medications
            mandatory: true
            details:
              -
                collection: medications
                fields:
                  - description
                  - administration
                  - carrier
      transport:
        questions:
          -
            name: mpv
            mandatory: true
      communication:
        questions:
          -
            name: hearing_speech_sight_issues
            mandatory: true
          -
            name: reading_writing_issues
            mandatory: true
      contact:
        questions:
          -
            name: healthcare_professional
            mandatory: true
            relevant_answers: :all
          -
            name: contact_number
            mandatory: true
            relevant_answers: :all
