# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0515c18a50b3819aea663a1df81d30f897d63254f25d40dc0fbf81cbd568c8fe02dc130f12f3ff0f1ca2fbf6246828f65580ad308aa75f6a8c5b2d56f1ddd0f4
  offenders_api: &offenders_api_devtest
    client_id: 2fc8075e00c430c9e4cb4431f6e10eea736e777d37ec1eb894bfaff050836f4c
    client_secret: 42668ed14388113ccd14d59a1e5721d5b62c6fbc5c7b7a8632a2446825e72d7b
    base_url: 'https://prisoners-api.herokuapp.com'

test:
  secret_key_base: b00b1364e73b972e9cb0f598ec47e0eaac1373d7ba7150380da281c13a828084ec8dfc6ee7240a34516d0c3c7c0a6d899752b29e1d5260c846d5de44805a401a
  offenders_api: *offenders_api_devtest

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  offenders_api:
    client_id: <%= ENV["OFFENDERS_API_CLIENT_ID"] %>
    client_secret: <%= ENV["OFFENDERS_API_CLIENT_SECRET"] %>
    base_url: 'https://prisoners-api.herokuapp.com'
